---
- name: LXC TEST | create cluster
  hosts: all
  vars:
    lxc_clones:
      - name: first
        template: ubuntu.trusty
        ip: 10.10.3.3

      - name: to_be_recreated
        template: ubuntu.trusty
        ip: 10.10.5.5

    lxc_forwarded_ports:
      - source: 2022
        target: 10.10.3.3:22

      - source: 2055
        target: 10.10.5.5:22
  roles:
    - lxc

- name: LXC TEST | destroy node
  hosts: all
  vars:
    container: to_be_recreated
  tasks:
    - include: roles/lxc/tasks/destroy.yml

- name: LXC TEST | recreate and add node to cluster
  hosts: all
  vars:
    lxc_clones:
      - name: to_be_recreated
        template: ubuntu.trusty
        ip: 10.10.5.5
      - name: added
        template: ubuntu.trusty
        ip: 10.10.4.4
  roles:
    - lxc

- name: LXC TEST | bastion usage
  hosts: all
  vars:
    rootfs: /var/lib/lxc/ubuntu.trusty/rootfs
  tasks:

#    - name: generate ssh key on host
#      user: name=vagrant generate_ssh_key=yes

#    - name: ensure .ssh is exists for root
#      file: path={{rootfs}}/root/.ssh state=directory

#    - name: add keys as authorized to base image
#      shell: "cat /home/vagrant/.ssh/id_rsa.pub >> {{rootfs}}/root/.ssh/authorized_keys"

    - name: add keys as authorized for root
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        path: "{{rootfs}}/root/.ssh/authorized_keys"
        manage_dir: no
